import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es' | 'fr' | 'it';

interface Translations {
    [key: string]: {
        [lang in Language]: string;
    };
}

export const translations: Translations = {
    // Navigation
    'nav.home': { pt: 'Início', en: 'Home', es: 'Inicio', fr: 'Accueil', it: 'Inizio' },
    'nav.about': { pt: 'Sobre', en: 'About', es: 'Acerca de', fr: 'À propos', it: 'Chi siamo' },
    'nav.courses': { pt: 'Cursos', en: 'Courses', es: 'Cursos', fr: 'Cours', it: 'Corsi' },
    'nav.mainCourses': { pt: 'Cursos Principais', en: 'Main Courses', es: 'Cursos Principales', fr: 'Cours Principaux', it: 'Corsi Principali' },
    'nav.specificCourses': { pt: 'Cursos Específicos', en: 'Specific Courses', es: 'Cursos Específicos', fr: 'Cours Spécifiques', it: 'Corsi Specifici' },
    'nav.corporateEnglish': { pt: 'Inglês para Empresas', en: 'Corporate English', es: 'Inglés para Empresas', fr: 'Anglais pour Entreprises', it: 'Inglese per Aziende' },
    'nav.plans': { pt: 'Planos', en: 'Plans', es: 'Planes', fr: 'Forfaits', it: 'Piani' },
    'nav.requestQuote': { pt: 'Solicitar Orçamento', en: 'Request Quote', es: 'Solicitar Cotización', fr: 'Demander un Devis', it: 'Richiedi Preventivo' },
    'nav.methodology': { pt: 'Metodologia', en: 'Methodology', es: 'Metodología', fr: 'Méthodologie', it: 'Metodologia' },

    // Hero
    'hero.badge': { pt: 'Referência em Inglês Profissional', en: 'Professional English Reference', es: 'Referencia en Inglés Profesional', fr: 'Référence en Anglais Professionnel', it: 'Riferimento in Inglese Professionale' },
    'hero.title1': { pt: 'Domine o Inglês e', en: 'Master English and', es: 'Domina el Inglés y', fr: 'Maîtrisez l\'Anglais et', it: 'Padroneggia l\'Inglese e' },
    'hero.title2': { pt: 'Impulsione sua Carreira', en: 'Boost Your Career', es: 'Impulsa tu Carrera', fr: 'Boostez Votre Carrière', it: 'Potenzia la Tua Carriera' },
    'hero.description1': { pt: 'Falar inglês muda destinos. Abre portas, cria oportunidades, conecta pessoas e transforma vidas. E é exatamente por isso que a Speak Online existe.', en: 'Speaking English changes destinies. It opens doors, creates opportunities, connects people, and transforms lives. And that\'s exactly why Speak Online exists.', es: 'Hablar inglés cambia destinos. Abre puertas, crea oportunidades, conecta personas y transforma vidas. Y es exactamente por eso que Speak Online existe.', fr: 'Parler anglais change les destins. Cela ouvre des portes, crée des opportunités, connecte les gens et transforme des vies. Et c\'est exactement pour cela que Speak Online existe.', it: 'Parlare inglese cambia i destini. Apre porte, crea opportunità, connette persone e trasforma vite. Ed è esattamente per questo che Speak Online esiste.' },
    'hero.description2': { pt: 'Acreditamos que fluência não acontece em silêncio. Ela nasce da prática, da coragem de tentar, da orientação certa e de um ambiente que acolhe, inspira e desenvolve. Aqui, cada aula é construída para que você fale, pense e sinta o inglês com naturalidade.', en: 'We believe fluency doesn\'t happen in silence. It comes from practice, the courage to try, the right guidance, and an environment that welcomes, inspires, and develops. Here, every class is built so you speak, think, and feel English naturally.', es: 'Creemos que la fluidez no sucede en silencio. Nace de la práctica, del coraje de intentar, de la orientación correcta y de un ambiente que acoge, inspira y desarrolla. Aquí, cada clase está construida para que hables, pienses y sientas el inglés con naturalidad.', fr: 'Nous croyons que la fluidité ne se produit pas en silence. Elle naît de la pratique, du courage d\'essayer, de la bonne orientation et d\'un environnement qui accueille, inspire et développe. Ici, chaque cours est conçu pour que vous parliez, pensiez et ressentiez l\'anglais naturellement.', it: 'Crediamo che la fluenza non avvenga in silenzio. Nasce dalla pratica, dal coraggio di provare, dalla giusta guida e da un ambiente che accoglie, ispira e sviluppa. Qui, ogni lezione è costruita perché tu parli, pensi e senta l\'inglese con naturalezza.' },
    'hero.globalFluency': { pt: 'Fluência Global', en: 'Global Fluency', es: 'Fluidez Global', fr: 'Aisance Mondiale', it: 'Fluenza Globale' },
    'hero.professionalCommunication': { pt: 'Comunicação profissional', en: 'Professional communication', es: 'Comunicación profesional', fr: 'Communication professionnelle', it: 'Comunicazione professionale' },
    'hero.fastResults': { pt: 'Resultados Rápidos', en: 'Fast Results', es: 'Resultados Rápidos', fr: 'Résultats Rapides', it: 'Risultati Rapidi' },
    'hero.provenMethod': { pt: 'Metodologia comprovada', en: 'Proven methodology', es: 'Metodología comprobada', fr: 'Méthodologie éprouvée', it: 'Metodologia comprovata' },
    'hero.formTitle': { pt: 'Solicite um Orçamento', en: 'Request a Quote', es: 'Solicita un Presupuesto', fr: 'Demandez un Devis', it: 'Richiedi un Preventivo' },
    'hero.formDescription': { pt: 'Descubra o plano ideal para seus objetivos', en: 'Discover the ideal plan for your goals', es: 'Descubre el plan ideal para tus objetivos', fr: 'Découvrez le plan idéal pour vos objectifs', it: 'Scopri il piano ideale per i tuoi obiettivi' },
    'hero.fullName': { pt: 'Nome completo', en: 'Full name', es: 'Nombre completo', fr: 'Nom complet', it: 'Nome completo' },
    'hero.yourName': { pt: 'Seu nome', en: 'Your name', es: 'Tu nombre', fr: 'Votre nom', it: 'Il tuo nome' },
    'hero.email': { pt: 'E-mail', en: 'Email', es: 'Correo electrónico', fr: 'E-mail', it: 'E-mail' },
    'hero.goalLabel': { pt: 'Seu objetivo com o inglês', en: 'Your English goal', es: 'Tu objetivo con el inglés', fr: 'Votre objectif avec l\'anglais', it: 'Il tuo obiettivo con l\'inglese' },
    'hero.goalPlaceholder': { pt: 'Ex: Melhorar comunicação em reuniões, preparar para entrevista...', en: 'E.g.: Improve meeting communication, prepare for interview...', es: 'Ej: Mejorar comunicación en reuniones, preparar para entrevista...', fr: 'Ex: Améliorer la communication en réunion, préparer un entretien...', it: 'Es: Migliorare la comunicazione nelle riunioni, prepararsi per un colloquio...' },
    'hero.submitButton': { pt: 'Receber Proposta Personalizada', en: 'Receive Personalized Proposal', es: 'Recibir Propuesta Personalizada', fr: 'Recevoir une Proposition Personnalisée', it: 'Ricevi Proposta Personalizzata' },
    'hero.responseTime': { pt: 'Resposta em até 24 horas úteis', en: 'Response within 24 business hours', es: 'Respuesta en hasta 24 horas hábiles', fr: 'Réponse sous 24 heures ouvrables', it: 'Risposta entro 24 ore lavorative' },
    'hero.requestSent': { pt: 'Solicitação enviada!', en: 'Request sent!', es: '¡Solicitud enviada!', fr: 'Demande envoyée!', it: 'Richiesta inviata!' },
    'hero.requestSentDesc': { pt: 'Entraremos em contato em breve.', en: 'We will contact you soon.', es: 'Nos pondremos en contacto pronto.', fr: 'Nous vous contacterons bientôt.', it: 'Ti contatteremo presto.' },

    // Courses
    'courses.title': { pt: 'Nossos', en: 'Our', es: 'Nuestros', fr: 'Nos', it: 'I nostri' },
    'courses.titleHighlight': { pt: 'Cursos', en: 'Courses', es: 'Cursos', fr: 'Cours', it: 'Corsi' },
    'courses.subtitle': { pt: 'Programas especializados para cada objetivo profissional', en: 'Specialized programs for each professional goal', es: 'Programas especializados para cada objetivo profesional', fr: 'Programmes spécialisés pour chaque objectif professionnel', it: 'Programmi specializzati per ogni obiettivo professionale' },
    'courses.conversation': { pt: 'Conversação', en: 'Conversation', es: 'Conversación', fr: 'Conversation', it: 'Conversazione' },
    'courses.conversationDesc': { pt: 'Desenvolva fluência natural em conversas do dia a dia e situações sociais.', en: 'Develop natural fluency in everyday conversations and social situations.', es: 'Desarrolla fluidez natural en conversaciones cotidianas y situaciones sociales.', fr: 'Développez une aisance naturelle dans les conversations quotidiennes et les situations sociales.', it: 'Sviluppa una fluenza naturale nelle conversazioni quotidiane e nelle situazioni sociali.' },
    'courses.professional': { pt: 'Inglês Profissional', en: 'Professional English', es: 'Inglés Profesional', fr: 'Anglais Professionnel', it: 'Inglese Professionale' },
    'courses.professionalDesc': { pt: 'Domine o inglês corporativo para reuniões, apresentações e negociações.', en: 'Master corporate English for meetings, presentations, and negotiations.', es: 'Domina el inglés corporativo para reuniones, presentaciones y negociaciones.', fr: 'Maîtrisez l\'anglais des affaires pour les réunions, présentations et négociations.', it: 'Padroneggia l\'inglese aziendale per riunioni, presentazioni e negoziazioni.' },
    'courses.travel': { pt: 'Inglês para Viagens', en: 'Travel English', es: 'Inglés para Viajes', fr: 'Anglais pour Voyages', it: 'Inglese per Viaggi' },
    'courses.travelDesc': { pt: 'Aprenda o essencial para viajar com confiança e aproveitar ao máximo.', en: 'Learn the essentials to travel with confidence and make the most of it.', es: 'Aprende lo esencial para viajar con confianza y aprovecharlo al máximo.', fr: 'Apprenez l\'essentiel pour voyager en confiance et en profiter au maximum.', it: 'Impara l\'essenziale per viaggiare con fiducia e trarne il massimo.' },
    'courses.interviews': { pt: 'Preparação para Entrevistas', en: 'Interview Preparation', es: 'Preparación para Entrevistas', fr: 'Préparation aux Entretiens', it: 'Preparazione per Colloqui' },
    'courses.interviewsDesc': { pt: 'Prepare-se para entrevistas em inglês e conquiste sua vaga internacional.', en: 'Prepare for English interviews and land your international position.', es: 'Prepárate para entrevistas en inglés y conquista tu puesto internacional.', fr: 'Préparez-vous aux entretiens en anglais et décrochez votre poste international.', it: 'Preparati per i colloqui in inglese e conquista la tua posizione internazionale.' },
    'courses.speakingIntensive': { pt: 'Speaking intensivo', en: 'Intensive speaking', es: 'Speaking intensivo', fr: 'Expression orale intensive', it: 'Speaking intensivo' },
    'courses.practicalVocabulary': { pt: 'Vocabulário prático', en: 'Practical vocabulary', es: 'Vocabulario práctico', fr: 'Vocabulaire pratique', it: 'Vocabolario pratico' },
    'courses.speakingConfidence': { pt: 'Confiança na fala', en: 'Speaking confidence', es: 'Confianza al hablar', fr: 'Confiance à l\'oral', it: 'Fiducia nel parlare' },
    'courses.businessEnglish': { pt: 'Business English', en: 'Business English', es: 'Business English', fr: 'Business English', it: 'Business English' },
    'courses.professionalEmails': { pt: 'Emails profissionais', en: 'Professional emails', es: 'Emails profesionales', fr: 'Emails professionnels', it: 'Email professionali' },
    'courses.meetingsCalls': { pt: 'Reuniões e calls', en: 'Meetings and calls', es: 'Reuniones y calls', fr: 'Réunions et calls', it: 'Riunioni e call' },
    'courses.realSituations': { pt: 'Situações reais', en: 'Real situations', es: 'Situaciones reales', fr: 'Situations réelles', it: 'Situazioni reali' },
    'courses.cultureEtiquette': { pt: 'Cultura e etiqueta', en: 'Culture and etiquette', es: 'Cultura y etiqueta', fr: 'Culture et étiquette', it: 'Cultura ed etichetta' },
    'courses.businessTravel': { pt: 'Viagens de negócios', en: 'Business travel', es: 'Viajes de negocios', fr: 'Voyages d\'affaires', it: 'Viaggi d\'affari' },
    'courses.mockInterviews': { pt: 'Mock interviews', en: 'Mock interviews', es: 'Mock interviews', fr: 'Entretiens simulés', it: 'Mock interviews' },
    'courses.responseTechniques': { pt: 'Técnicas de resposta', en: 'Response techniques', es: 'Técnicas de respuesta', fr: 'Techniques de réponse', it: 'Tecniche di risposta' },
    'courses.technicalVocabulary': { pt: 'Vocabulário técnico', en: 'Technical vocabulary', es: 'Vocabulario técnico', fr: 'Vocabulaire technique', it: 'Vocabolario tecnico' },

    // Countries Section
    'countries.title': { pt: 'Países onde', en: 'Countries where we', es: 'Países donde', fr: 'Pays où nous', it: 'Paesi dove' },
    'countries.titleHighlight': { pt: 'Atuamos', en: 'Operate', es: 'Actuamos', fr: 'Opérons', it: 'Operiamo' },
    'countries.subtitle': { pt: 'Nossa metodologia alcança alunos em diversos países ao redor do mundo', en: 'Our methodology reaches students in various countries around the world', es: 'Nuestra metodología alcanza estudiantes en diversos países alrededor del mundo', fr: 'Notre méthodologie atteint des étudiants dans divers pays du monde', it: 'La nostra metodologia raggiunge studenti in vari paesi del mondo' },

    // Journey Section
    'journey.title': { pt: 'Jornada do', en: 'The', es: 'Jornada del', fr: 'Parcours de l\'', it: 'Percorso dello' },
    'journey.titleHighlight': { pt: 'Aluno Speak', en: 'Speak Student Journey', es: 'Alumno Speak', fr: 'Élève Speak', it: 'Studente Speak' },
    'journey.subtitle': { pt: 'Do primeiro contato à fluência: seu caminho estruturado para o sucesso', en: 'From first contact to fluency: your structured path to success', es: 'Del primer contacto a la fluidez: tu camino estructurado hacia el éxito', fr: 'Du premier contact à la fluidité: votre chemin structuré vers le succès', it: 'Dal primo contatto alla fluenza: il tuo percorso strutturato verso il successo' },
    'journey.diagnosis': { pt: 'Diagnóstico', en: 'Diagnosis', es: 'Diagnóstico', fr: 'Diagnostic', it: 'Diagnosi' },
    'journey.diagnosisDesc': { pt: 'Avaliação completa do seu nível e objetivos', en: 'Complete assessment of your level and goals', es: 'Evaluación completa de tu nivel y objetivos', fr: 'Évaluation complète de votre niveau et objectifs', it: 'Valutazione completa del tuo livello e obiettivi' },
    'journey.personalizedPlan': { pt: 'Plano Personalizado', en: 'Personalized Plan', es: 'Plan Personalizado', fr: 'Plan Personnalisé', it: 'Piano Personalizzato' },
    'journey.personalizedPlanDesc': { pt: 'Criamos uma jornada sob medida para você', en: 'We create a tailored journey for you', es: 'Creamos un viaje a medida para ti', fr: 'Nous créons un parcours sur mesure pour vous', it: 'Creiamo un percorso su misura per te' },
    'journey.interactiveClasses': { pt: 'Aulas Interativas', en: 'Interactive Classes', es: 'Clases Interactivas', fr: 'Cours Interactifs', it: 'Lezioni Interattive' },
    'journey.interactiveClassesDesc': { pt: 'Aprenda com metodologia moderna e engajadora', en: 'Learn with modern and engaging methodology', es: 'Aprende con metodología moderna y atractiva', fr: 'Apprenez avec une méthodologie moderne et engageante', it: 'Impara con metodologia moderna e coinvolgente' },
    'journey.constantPractice': { pt: 'Prática Constante', en: 'Constant Practice', es: 'Práctica Constante', fr: 'Pratique Constante', it: 'Pratica Costante' },
    'journey.constantPracticeDesc': { pt: 'Conversação e exercícios práticos diários', en: 'Daily conversation and practical exercises', es: 'Conversación y ejercicios prácticos diarios', fr: 'Conversation et exercices pratiques quotidiens', it: 'Conversazione ed esercizi pratici quotidiani' },
    'journey.achievements': { pt: 'Conquistas', en: 'Achievements', es: 'Logros', fr: 'Réussites', it: 'Conquiste' },
    'journey.achievementsDesc': { pt: 'Acompanhe sua evolução com metas claras', en: 'Track your progress with clear goals', es: 'Sigue tu evolución con metas claras', fr: 'Suivez votre évolution avec des objectifs clairs', it: 'Segui la tua evoluzione con obiettivi chiari' },
    'journey.fluency': { pt: 'Fluência', en: 'Fluency', es: 'Fluidez', fr: 'Aisance', it: 'Fluenza' },
    'journey.fluencyDesc': { pt: 'Domine o inglês e alcance seus objetivos', en: 'Master English and achieve your goals', es: 'Domina el inglés y alcanza tus objetivos', fr: 'Maîtrisez l\'anglais et atteignez vos objectifs', it: 'Padroneggia l\'inglese e raggiungi i tuoi obiettivi' },
    'journey.cta': { pt: '✨ Comece sua jornada hoje e veja resultados em semanas, não anos', en: '✨ Start your journey today and see results in weeks, not years', es: '✨ Comienza tu viaje hoy y ve resultados en semanas, no años', fr: '✨ Commencez votre parcours aujourd\'hui et voyez des résultats en semaines, pas en années', it: '✨ Inizia il tuo percorso oggi e vedi risultati in settimane, non anni' },
    'journey.whatsappMessage': { pt: 'Olá! Quero começar minha jornada de aprendizado de inglês.', en: 'Hello! I want to start my English learning journey.', es: '¡Hola! Quiero comenzar mi viaje de aprendizaje de inglés.', fr: 'Bonjour! Je veux commencer mon parcours d\'apprentissage de l\'anglais.', it: 'Ciao! Voglio iniziare il mio percorso di apprendimento dell\'inglese.' },

    // Pricing Section
    'pricing.title': { pt: 'Planos de', en: 'Study', es: 'Planes de', fr: 'Forfaits d\'', it: 'Piani di' },
    'pricing.titleHighlight': { pt: 'Estudo', en: 'Plans', es: 'Estudio', fr: 'Études', it: 'Studio' },
    'pricing.subtitle': { pt: 'Escolha o plano ideal para seus objetivos', en: 'Choose the ideal plan for your goals', es: 'Elige el plan ideal para tus objetivos', fr: 'Choisissez le forfait idéal pour vos objectifs', it: 'Scegli il piano ideale per i tuoi obiettivi' },
    'pricing.basic': { pt: 'Básico', en: 'Basic', es: 'Básico', fr: 'Basique', it: 'Base' },
    'pricing.intermediate': { pt: 'Intermediário', en: 'Intermediate', es: 'Intermedio', fr: 'Intermédiaire', it: 'Intermedio' },
    'pricing.mostPopular': { pt: 'Mais Popular', en: 'Most Popular', es: 'Más Popular', fr: 'Le Plus Populaire', it: 'Più Popolare' },
    'pricing.startNow': { pt: 'Começar Agora', en: 'Start Now', es: 'Comenzar Ahora', fr: 'Commencer Maintenant', it: 'Inizia Ora' },
    'pricing.guarantee': { pt: 'Todos os planos incluem garantia de 7 dias e podem ser cancelados a qualquer momento', en: 'All plans include 7-day guarantee and can be cancelled at any time', es: 'Todos los planes incluyen garantía de 7 días y pueden cancelarse en cualquier momento', fr: 'Tous les forfaits incluent une garantie de 7 jours et peuvent être annulés à tout moment', it: 'Tutti i piani includono garanzia di 7 giorni e possono essere cancellati in qualsiasi momento' },

    // Pricing Plans
    'pricing.plans.essential': { pt: 'Essencial', en: 'Essential', es: 'Esencial', fr: 'Essentiel', it: 'Essenziale' },
    'pricing.plans.professional': { pt: 'Profissional', en: 'Professional', es: 'Profesional', fr: 'Professionnel', it: 'Professionale' },
    'pricing.plans.executive': { pt: 'Executive', en: 'Executive', es: 'Executive', fr: 'Executive', it: 'Executive' },
    'pricing.plans.essentialDesc': { pt: 'Ideal para quem está começando', en: 'Ideal for beginners', es: 'Ideal para quienes están comenzando', fr: 'Idéal pour les débutants', it: 'Ideale per chi sta iniziando' },
    'pricing.plans.professionalDescBasic': { pt: 'Mais popular entre iniciantes', en: 'Most popular among beginners', es: 'Más popular entre principiantes', fr: 'Le plus populaire chez les débutants', it: 'Più popolare tra i principianti' },
    'pricing.plans.executiveDescBasic': { pt: 'Para quem quer acelerar', en: 'For those who want to accelerate', es: 'Para quienes quieren acelerar', fr: 'Pour ceux qui veulent accélérer', it: 'Per chi vuole accelerare' },
    'pricing.plans.essentialDescInter': { pt: 'Para consolidar seu inglês', en: 'To consolidate your English', es: 'Para consolidar tu inglés', fr: 'Pour consolider votre anglais', it: 'Per consolidare il tuo inglese' },
    'pricing.plans.professionalDescInter': { pt: 'Mais popular entre profissionais', en: 'Most popular among professionals', es: 'Más popular entre profesionales', fr: 'Le plus populaire chez les professionnels', it: 'Più popolare tra i professionisti' },
    'pricing.plans.executiveDescInter': { pt: 'Para quem busca resultados máximos', en: 'For those seeking maximum results', es: 'Para quienes buscan resultados máximos', fr: 'Pour ceux qui recherchent des résultats maximaux', it: 'Per chi cerca risultati massimi' },

    // Pricing Features
    'pricing.features.weekly1': { pt: '1 aula semanal (50min)', en: '1 weekly class (50min)', es: '1 clase semanal (50min)', fr: '1 cours hebdomadaire (50min)', it: '1 lezione settimanale (50min)' },
    'pricing.features.weekly2': { pt: '2 aulas semanais (50min)', en: '2 weekly classes (50min)', es: '2 clases semanales (50min)', fr: '2 cours hebdomadaires (50min)', it: '2 lezioni settimanali (50min)' },
    'pricing.features.weekly3': { pt: '3 aulas semanais (50min)', en: '3 weekly classes (50min)', es: '3 clases semanales (50min)', fr: '3 cours hebdomadaires (50min)', it: '3 lezioni settimanali (50min)' },
    'pricing.features.weekly5': { pt: '5 aulas semanais (50min)', en: '5 weekly classes (50min)', es: '5 clases semanales (50min)', fr: '5 cours hebdomadaires (50min)', it: '5 lezioni settimanali (50min)' },
    'pricing.features.digitalMaterial': { pt: 'Material didático digital', en: 'Digital teaching material', es: 'Material didáctico digital', fr: 'Matériel pédagogique numérique', it: 'Materiale didattico digitale' },
    'pricing.features.platformAccess': { pt: 'Acesso à plataforma', en: 'Platform access', es: 'Acceso a la plataforma', fr: 'Accès à la plateforme', it: 'Accesso alla piattaforma' },
    'pricing.features.conversationGroup': { pt: 'Grupo de conversação', en: 'Conversation group', es: 'Grupo de conversación', fr: 'Groupe de conversation', it: 'Gruppo di conversazione' },
    'pricing.features.emailSupport': { pt: 'Suporte por email', en: 'Email support', es: 'Soporte por email', fr: 'Support par email', it: 'Supporto via email' },
    'pricing.features.completeMaterial': { pt: 'Material didático completo', en: 'Complete teaching material', es: 'Material didáctico completo', fr: 'Matériel pédagogique complet', it: 'Materiale didattico completo' },
    'pricing.features.fullPlatformAccess': { pt: 'Acesso total à plataforma', en: 'Full platform access', es: 'Acceso total a la plataforma', fr: 'Accès complet à la plateforme', it: 'Accesso completo alla piattaforma' },
    'pricing.features.conversationGroups': { pt: 'Grupos de conversação', en: 'Conversation groups', es: 'Grupos de conversación', fr: 'Groupes de conversation', it: 'Gruppi di conversazione' },
    'pricing.features.reinforcementClasses': { pt: 'Aulas de reforço', en: 'Reinforcement classes', es: 'Clases de refuerzo', fr: 'Cours de renforcement', it: 'Lezioni di rinforzo' },
    'pricing.features.prioritySupport': { pt: 'Suporte prioritário', en: 'Priority support', es: 'Soporte prioritario', fr: 'Support prioritaire', it: 'Supporto prioritario' },
    'pricing.features.premiumMaterial': { pt: 'Material premium', en: 'Premium material', es: 'Material premium', fr: 'Matériel premium', it: 'Materiale premium' },
    'pricing.features.vipPlatformAccess': { pt: 'Acesso VIP à plataforma', en: 'VIP platform access', es: 'Acceso VIP a la plataforma', fr: 'Accès VIP à la plateforme', it: 'Accesso VIP alla piattaforma' },
    'pricing.features.weeklyConversation': { pt: 'Conversação semanal', en: 'Weekly conversation', es: 'Conversación semanal', fr: 'Conversation hebdomadaire', it: 'Conversazione settimanale' },
    'pricing.features.studyCoaching': { pt: 'Coaching de estudos', en: 'Study coaching', es: 'Coaching de estudios', fr: 'Coaching d\'études', it: 'Coaching di studi' },
    'pricing.features.support247': { pt: 'Suporte 24/7', en: '24/7 support', es: 'Soporte 24/7', fr: 'Support 24/7', it: 'Supporto 24/7' },
    'pricing.features.advancedMaterial': { pt: 'Material didático avançado', en: 'Advanced teaching material', es: 'Material didáctico avanzado', fr: 'Matériel pédagogique avancé', it: 'Materiale didattico avanzato' },
    'pricing.features.monthlySimulations': { pt: 'Simulados mensais', en: 'Monthly mock tests', es: 'Simulacros mensuales', fr: 'Tests blancs mensuels', it: 'Simulazioni mensili' },
    'pricing.features.unlimitedConversation': { pt: 'Grupos de conversação ilimitados', en: 'Unlimited conversation groups', es: 'Grupos de conversación ilimitados', fr: 'Groupes de conversation illimités', it: 'Gruppi di conversazione illimitati' },
    'pricing.features.simulationsAndCerts': { pt: 'Simulados e certificações', en: 'Mock tests and certifications', es: 'Simulacros y certificaciones', fr: 'Tests blancs et certifications', it: 'Simulazioni e certificazioni' },
    'pricing.features.phdTeachers': { pt: 'Professores PhD ou mestres', en: 'PhD or master\'s teachers', es: 'Profesores PhD o másters', fr: 'Professeurs PhD ou masters', it: 'Insegnanti PhD o master' },
    'pricing.features.customPremiumMaterial': { pt: 'Material premium personalizado', en: 'Custom premium material', es: 'Material premium personalizado', fr: 'Matériel premium personnalisé', it: 'Materiale premium personalizzato' },
    'pricing.features.dailyConversation': { pt: 'Conversação diária', en: 'Daily conversation', es: 'Conversación diaria', fr: 'Conversation quotidienne', it: 'Conversazione quotidiana' },
    'pricing.features.careerCoaching': { pt: 'Coaching de carreira', en: 'Career coaching', es: 'Coaching de carrera', fr: 'Coaching de carrière', it: 'Coaching di carriera' },
    'pricing.features.certPreparation': { pt: 'Preparação para certificações', en: 'Certification preparation', es: 'Preparación para certificaciones', fr: 'Préparation aux certifications', it: 'Preparazione alle certificazioni' },
    'pricing.features.internationalNetworking': { pt: 'Networking internacional', en: 'International networking', es: 'Networking internacional', fr: 'Networking international', it: 'Networking internazionale' },

    // Stats Section
    'stats.title': { pt: 'Resultados que', en: 'Results that', es: 'Resultados que', fr: 'Des résultats qui', it: 'Risultati che' },
    'stats.titleHighlight': { pt: 'Comprovam', en: 'Prove It', es: 'Comprueban', fr: 'Le Prouvent', it: 'Lo Dimostrano' },
    'stats.subtitle': { pt: 'Números que refletem nossa excelência e o sucesso dos nossos alunos', en: 'Numbers that reflect our excellence and our students\' success', es: 'Números que reflejan nuestra excelencia y el éxito de nuestros alumnos', fr: 'Des chiffres qui reflètent notre excellence et le succès de nos élèves', it: 'Numeri che riflettono la nostra eccellenza e il successo dei nostri studenti' },
    'stats.activeStudents': { pt: 'Alunos Ativos', en: 'Active Students', es: 'Alumnos Activos', fr: 'Étudiants Actifs', it: 'Studenti Attivi' },
    'stats.approvalRate': { pt: 'Taxa de Aprovação', en: 'Approval Rate', es: 'Tasa de Aprobación', fr: 'Taux de Réussite', it: 'Tasso di Approvazione' },
    'stats.averageRating': { pt: 'Avaliação Média', en: 'Average Rating', es: 'Calificación Promedio', fr: 'Note Moyenne', it: 'Valutazione Media' },
    'stats.careerGrowth': { pt: 'Crescimento de Carreira', en: 'Career Growth', es: 'Crecimiento de Carrera', fr: 'Croissance de Carrière', it: 'Crescita di Carriera' },
    'stats.experience': { pt: 'Anos de Experiência', en: 'Years of Experience', es: 'Años de Experiencia', fr: 'Années d\'Expérience', it: 'Anni di Esperienza' },
    'stats.students': { pt: 'Alunos Formados', en: 'Graduated Students', es: 'Alumnos Graduados', fr: 'Étudiants Diplômés', it: 'Studenti Laureati' },
    'stats.satisfaction': { pt: 'Satisfação', en: 'Satisfaction', es: 'Satisfacción', fr: 'Satisfaction', it: 'Soddisfazione' },
    'stats.teachers': { pt: 'Professores', en: 'Teachers', es: 'Profesores', fr: 'Professeurs', it: 'Insegnanti' },

    // Testimonials Section
    'testimonials.title': { pt: 'Histórias de', en: 'Success', es: 'Historias de', fr: 'Histoires de', it: 'Storie di' },
    'testimonials.titleHighlight': { pt: 'Sucesso', en: 'Stories', es: 'Éxito', fr: 'Succès', it: 'Successo' },
    'testimonials.subtitle': { pt: 'Veja como nossos alunos transformaram suas carreiras', en: 'See how our students transformed their careers', es: 'Ve cómo nuestros alumnos transformaron sus carreras', fr: 'Voyez comment nos élèves ont transformé leurs carrières', it: 'Scopri come i nostri studenti hanno trasformato le loro carriere' },
    'testimonials.watchVideo': { pt: 'Assistir depoimento de', en: 'Watch testimonial from', es: 'Ver testimonio de', fr: 'Regarder le témoignage de', it: 'Guarda la testimonianza di' },

    // FAQ Section
    'faq.title': { pt: 'Perguntas', en: 'Frequently', es: 'Preguntas', fr: 'Questions', it: 'Domande' },
    'faq.titleHighlight': { pt: 'Frequentes', en: 'Asked Questions', es: 'Frecuentes', fr: 'Fréquentes', it: 'Frequenti' },
    'faq.subtitle': { pt: 'Tire suas dúvidas sobre nossos cursos e metodologia', en: 'Get your questions answered about our courses and methodology', es: 'Resuelve tus dudas sobre nuestros cursos y metodología', fr: 'Répondez à vos questions sur nos cours et notre méthodologie', it: 'Risolvi i tuoi dubbi sui nostri corsi e metodologia' },
    'faq.stillQuestions': { pt: 'Ainda tem dúvidas?', en: 'Still have questions?', es: '¿Aún tienes dudas?', fr: 'Vous avez encore des questions?', it: 'Hai ancora domande?' },
    'faq.contactUs': { pt: 'Entre em contato conosco →', en: 'Contact us →', es: 'Contáctanos →', fr: 'Contactez-nous →', it: 'Contattaci →' },
    'faq.q1': { pt: 'Como funciona a metodologia da Speak Online?', en: 'How does Speak Online\'s methodology work?', es: '¿Cómo funciona la metodología de Speak Online?', fr: 'Comment fonctionne la méthodologie de Speak Online?', it: 'Come funziona la metodologia di Speak Online?' },
    'faq.a1': { pt: 'Nossa metodologia combina aulas ao vivo com professores especializados, material didático moderno e prática constante. Focamos em conversação e situações reais do mercado de trabalho, garantindo que você aprenda inglês aplicável ao seu dia a dia profissional.', en: 'Our methodology combines live classes with specialized teachers, modern teaching materials, and constant practice. We focus on conversation and real work situations, ensuring you learn English applicable to your professional daily life.', es: 'Nuestra metodología combina clases en vivo con profesores especializados, material didáctico moderno y práctica constante. Nos enfocamos en conversación y situaciones reales del mercado laboral, garantizando que aprendas inglés aplicable a tu día a día profesional.', fr: 'Notre méthodologie combine des cours en direct avec des professeurs spécialisés, du matériel pédagogique moderne et une pratique constante. Nous nous concentrons sur la conversation et les situations réelles du marché du travail, garantissant que vous apprenez un anglais applicable à votre vie professionnelle quotidienne.', it: 'La nostra metodologia combina lezioni dal vivo con insegnanti specializzati, materiale didattico moderno e pratica costante. Ci concentriamo sulla conversazione e situazioni reali del mercato del lavoro, garantendo che impari l\'inglese applicabile alla tua vita professionale quotidiana.' },
    'faq.q2': { pt: 'Quanto tempo leva para alcançar a fluência?', en: 'How long does it take to achieve fluency?', es: '¿Cuánto tiempo lleva alcanzar la fluidez?', fr: 'Combien de temps faut-il pour atteindre la fluidité?', it: 'Quanto tempo ci vuole per raggiungere la fluenza?' },
    'faq.a2': { pt: 'O tempo varia de acordo com seu nível inicial e dedicação. Em média, alunos iniciantes alcançam conversação básica em 3-6 meses e fluência intermediária em 12-18 meses. Nosso método acelerado e prática constante permitem resultados mais rápidos que cursos tradicionais.', en: 'The time varies according to your initial level and dedication. On average, beginner students achieve basic conversation in 3-6 months and intermediate fluency in 12-18 months. Our accelerated method and constant practice allow for faster results than traditional courses.', es: 'El tiempo varía según tu nivel inicial y dedicación. En promedio, los alumnos principiantes alcanzan conversación básica en 3-6 meses y fluidez intermedia en 12-18 meses. Nuestro método acelerado y práctica constante permiten resultados más rápidos que los cursos tradicionales.', fr: 'Le temps varie selon votre niveau initial et votre dévouement. En moyenne, les étudiants débutants atteignent une conversation de base en 3-6 mois et une aisance intermédiaire en 12-18 mois. Notre méthode accélérée et la pratique constante permettent des résultats plus rapides que les cours traditionnels.', it: 'Il tempo varia in base al tuo livello iniziale e alla dedizione. In media, gli studenti principianti raggiungono una conversazione di base in 3-6 mesi e una fluenza intermedia in 12-18 mesi. Il nostro metodo accelerato e la pratica costante permettono risultati più rapidi dei corsi tradizionali.' },
    'faq.q3': { pt: 'Os professores são nativos?', en: 'Are the teachers native speakers?', es: '¿Los profesores son nativos?', fr: 'Les professeurs sont-ils natifs?', it: 'Gli insegnanti sono madrelingua?' },
    'faq.a3': { pt: 'Trabalhamos com professores nativos e brasileiros com certificações internacionais (CELTA, TESOL, Cambridge). Todos têm experiência em inglês corporativo e passam por rigoroso processo de seleção.', en: 'We work with native and Brazilian teachers with international certifications (CELTA, TESOL, Cambridge). All have experience in corporate English and go through a rigorous selection process.', es: 'Trabajamos con profesores nativos y brasileños con certificaciones internacionales (CELTA, TESOL, Cambridge). Todos tienen experiencia en inglés corporativo y pasan por un riguroso proceso de selección.', fr: 'Nous travaillons avec des professeurs natifs et brésiliens titulaires de certifications internationales (CELTA, TESOL, Cambridge). Tous ont de l\'expérience en anglais des affaires et passent par un processus de sélection rigoureux.', it: 'Lavoriamo con insegnanti nativi e brasiliani con certificazioni internazionali (CELTA, TESOL, Cambridge). Tutti hanno esperienza nell\'inglese aziendale e passano attraverso un rigoroso processo di selezione.' },
    'faq.q4': { pt: 'Posso mudar de plano depois?', en: 'Can I change my plan later?', es: '¿Puedo cambiar de plan después?', fr: 'Puis-je changer de forfait plus tard?', it: 'Posso cambiare piano dopo?' },
    'faq.a4': { pt: 'Sim! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento. As mudanças entram em vigor no próximo ciclo de cobrança, sem taxas adicionais.', en: 'Yes! You can upgrade or downgrade your plan at any time. Changes take effect in the next billing cycle, with no additional fees.', es: '¡Sí! Puedes hacer upgrade o downgrade de tu plan en cualquier momento. Los cambios entran en vigor en el próximo ciclo de facturación, sin cargos adicionales.', fr: 'Oui! Vous pouvez mettre à niveau ou rétrograder votre forfait à tout moment. Les changements prennent effet au prochain cycle de facturation, sans frais supplémentaires.', it: 'Sì! Puoi fare upgrade o downgrade del tuo piano in qualsiasi momento. Le modifiche entrano in vigore nel prossimo ciclo di fatturazione, senza costi aggiuntivi.' },
    'faq.q5': { pt: 'Como são as aulas? Individuais ou em grupo?', en: 'What are the classes like? Individual or group?', es: '¿Cómo son las clases? ¿Individuales o en grupo?', fr: 'Comment sont les cours? Individuels ou en groupe?', it: 'Come sono le lezioni? Individuali o di gruppo?' },
    'faq.a5': { pt: 'Oferecemos ambos formatos. As aulas principais são em pequenos grupos (máx. 6 alunos) para garantir atenção individualizada. Planos superiores incluem aulas particulares e sessões de coaching personalizadas.', en: 'We offer both formats. Main classes are in small groups (max. 6 students) to ensure individualized attention. Higher plans include private classes and personalized coaching sessions.', es: 'Ofrecemos ambos formatos. Las clases principales son en grupos pequeños (máx. 6 alumnos) para garantizar atención individualizada. Los planes superiores incluyen clases particulares y sesiones de coaching personalizadas.', fr: 'Nous proposons les deux formats. Les cours principaux sont en petits groupes (max. 6 étudiants) pour garantir une attention individualisée. Les forfaits supérieurs comprennent des cours particuliers et des séances de coaching personnalisées.', it: 'Offriamo entrambi i formati. Le lezioni principali sono in piccoli gruppi (max. 6 studenti) per garantire attenzione individualizzata. I piani superiori includono lezioni private e sessioni di coaching personalizzate.' },
    'faq.q6': { pt: 'Vocês oferecem certificado?', en: 'Do you offer a certificate?', es: '¿Ofrecen certificado?', fr: 'Offrez-vous un certificat?', it: 'Offrite un certificato?' },
    'faq.a6': { pt: 'Sim, oferecemos certificado de conclusão de cada nível. Além disso, preparamos alunos para certificações internacionais como TOEFL, IELTS e Cambridge (custo da prova não incluso).', en: 'Yes, we offer a completion certificate for each level. Additionally, we prepare students for international certifications such as TOEFL, IELTS, and Cambridge (exam cost not included).', es: 'Sí, ofrecemos certificado de conclusión de cada nivel. Además, preparamos alumnos para certificaciones internacionales como TOEFL, IELTS y Cambridge (costo del examen no incluido).', fr: 'Oui, nous offrons un certificat de fin d\'études pour chaque niveau. De plus, nous préparons les étudiants aux certifications internationales telles que TOEFL, IELTS et Cambridge (coût de l\'examen non inclus).', it: 'Sì, offriamo un certificato di completamento per ogni livello. Inoltre, prepariamo gli studenti per certificazioni internazionali come TOEFL, IELTS e Cambridge (costo dell\'esame non incluso).' },
    'faq.q7': { pt: 'E se eu perder uma aula?', en: 'What if I miss a class?', es: '¿Y si pierdo una clase?', fr: 'Et si je manque un cours?', it: 'E se perdo una lezione?' },
    'faq.a7': { pt: 'Todas as aulas ficam gravadas na plataforma por 30 dias. Você também pode reagendar com até 24h de antecedência sem custos adicionais. Temos horários flexíveis de manhã, tarde e noite.', en: 'All classes are recorded on the platform for 30 days. You can also reschedule with up to 24h notice at no additional cost. We have flexible morning, afternoon, and evening schedules.', es: 'Todas las clases quedan grabadas en la plataforma por 30 días. También puedes reprogramar con hasta 24h de anticipación sin costos adicionales. Tenemos horarios flexibles de mañana, tarde y noche.', fr: 'Tous les cours sont enregistrés sur la plateforme pendant 30 jours. Vous pouvez également reprogrammer avec un préavis de 24h sans frais supplémentaires. Nous avons des horaires flexibles le matin, l\'après-midi et le soir.', it: 'Tutte le lezioni vengono registrate sulla piattaforma per 30 giorni. Puoi anche riprogrammare con preavviso di 24h senza costi aggiuntivi. Abbiamo orari flessibili mattina, pomeriggio e sera.' },
    'faq.q8': { pt: 'Qual a política de cancelamento?', en: 'What is the cancellation policy?', es: '¿Cuál es la política de cancelación?', fr: 'Quelle est la politique d\'annulation?', it: 'Qual è la politica di cancellazione?' },
    'faq.a8': { pt: 'Oferecemos garantia de 7 dias. Se não ficar satisfeito, devolvemos seu investimento integralmente. Após esse período, você pode cancelar a qualquer momento, sem multas ou taxas de cancelamento.', en: 'We offer a 7-day guarantee. If you\'re not satisfied, we\'ll refund your investment in full. After that period, you can cancel at any time, without fines or cancellation fees.', es: 'Ofrecemos garantía de 7 días. Si no quedas satisfecho, devolvemos tu inversión íntegramente. Después de ese período, puedes cancelar en cualquier momento, sin multas ni tarifas de cancelación.', fr: 'Nous offrons une garantie de 7 jours. Si vous n\'êtes pas satisfait, nous remboursons intégralement votre investissement. Après cette période, vous pouvez annuler à tout moment, sans pénalités ni frais d\'annulation.', it: 'Offriamo una garanzia di 7 giorni. Se non sei soddisfatto, rimborsiamo completamente il tuo investimento. Dopo questo periodo, puoi cancellare in qualsiasi momento, senza penali o spese di cancellazione.' },

    // About Page
    'about.title': { pt: 'Sobre a', en: 'About', es: 'Sobre', fr: 'À propos de', it: 'Chi siamo' },
    'about.description': { pt: 'Há mais de 20 anos levando fluência em inglês em tempo recorde de maneira simples e direta, conectando profissionais brasileiros às melhores oportunidades do mundo.', en: 'For over 20 years bringing English fluency in record time in a simple and direct way, connecting Brazilian professionals to the best opportunities in the world.', es: 'Hace más de 20 años llevando fluidez en inglés en tiempo récord de manera simple y directa, conectando profesionales brasileños a las mejores oportunidades del mundo.', fr: 'Depuis plus de 20 ans, nous apportons la maîtrise de l\'anglais en un temps record de manière simple et directe, connectant les professionnels brésiliens aux meilleures opportunités du monde.', it: 'Da oltre 20 anni portiamo la fluenza in inglese in tempo record in modo semplice e diretto, collegando i professionisti brasiliani alle migliori opportunità del mondo.' },
    'about.missionTitle': { pt: 'Nossa Missão', en: 'Our Mission', es: 'Nuestra Misión', fr: 'Notre Mission', it: 'La Nostra Missione' },
    'about.missionDesc': { pt: 'Transformar vidas pela oralidade. Como instituição especializada em alta performance na língua inglesa, a Speak Online International oferece uma experiência de aprendizagem leve, inteligente e fundamentada em ciência. Capacitar cada aluno a falar inglês com autonomia, segurança e confiança é o centro de tudo o que fazemos.', en: 'Transform lives through speaking. As an institution specialized in high performance in the English language, Speak Online International offers a light, intelligent learning experience grounded in science. Empowering each student to speak English with autonomy, security, and confidence is at the center of everything we do.', es: 'Transformar vidas a través de la oralidad. Como institución especializada en alto rendimiento en el idioma inglés, Speak Online International ofrece una experiencia de aprendizaje ligera, inteligente y fundamentada en ciencia. Capacitar a cada alumno para hablar inglés con autonomía, seguridad y confianza es el centro de todo lo que hacemos.', fr: 'Transformer des vies par l\'oral. En tant qu\'institution spécialisée dans la haute performance en langue anglaise, Speak Online International offre une expérience d\'apprentissage légère, intelligente et fondée sur la science. Permettre à chaque élève de parler anglais avec autonomie, sécurité et confiance est au cœur de tout ce que nous faisons.', it: 'Trasformare vite attraverso l\'oralità. Come istituzione specializzata in alte prestazioni nella lingua inglese, Speak Online International offre un\'esperienza di apprendimento leggera, intelligente e basata sulla scienza. Permettere a ogni studente di parlare inglese con autonomia, sicurezza e fiducia è al centro di tutto ciò che facciamo.' },
    'about.visionTitle': { pt: 'Nossa Visão', en: 'Our Vision', es: 'Nuestra Visión', fr: 'Notre Vision', it: 'La Nostra Visione' },
    'about.visionDesc': { pt: 'Ser a instituição de referência global em ensino de inglês focado em oralidade, unindo neurociência, tecnologia com propósito e uma metodologia autoral que entrega fluência real, mensurável e sustentável. Nossa visão é elevar o padrão internacional do aprendizado de idiomas e formar comunicadores de alta performance.', en: 'To be the global reference institution in English teaching focused on speaking, combining neuroscience, purposeful technology, and an original methodology that delivers real, measurable, and sustainable fluency. Our vision is to raise the international standard of language learning and train high-performance communicators.', es: 'Ser la institución de referencia global en enseñanza de inglés enfocada en oralidad, uniendo neurociencia, tecnología con propósito y una metodología autoral que entrega fluidez real, medible y sostenible. Nuestra visión es elevar el estándar internacional del aprendizaje de idiomas y formar comunicadores de alto rendimiento.', fr: 'Être l\'institution de référence mondiale dans l\'enseignement de l\'anglais axé sur l\'oral, combinant neuroscience, technologie avec un objectif et une méthodologie originale qui offre une fluidité réelle, mesurable et durable. Notre vision est d\'élever la norme internationale de l\'apprentissage des langues et de former des communicateurs de haute performance.', it: 'Essere l\'istituzione di riferimento globale nell\'insegnamento dell\'inglese focalizzato sull\'oralità, unendo neuroscienza, tecnologia con uno scopo e una metodologia originale che offre fluenza reale, misurabile e sostenibile. La nostra visione è elevare lo standard internazionale dell\'apprendimento delle lingue e formare comunicatori ad alte prestazioni.' },
    'about.valuesTitle': { pt: 'Nossos', en: 'Our', es: 'Nuestros', fr: 'Nos', it: 'I Nostri' },
    'about.valuesTitleHighlight': { pt: 'Valores', en: 'Values', es: 'Valores', fr: 'Valeurs', it: 'Valori' },
    'about.valuesSubtitle': { pt: 'Os pilares que guiam cada decisão e interação na Speak Online', en: 'The pillars that guide every decision and interaction at Speak Online', es: 'Los pilares que guían cada decisión e interacción en Speak Online', fr: 'Les piliers qui guident chaque décision et interaction chez Speak Online', it: 'I pilastri che guidano ogni decisione e interazione a Speak Online' },

    // Values
    'value1.title': { pt: 'A fala transforma', en: 'Speaking transforms', es: 'El habla transforma', fr: 'La parole transforme', it: 'Il parlare trasforma' },
    'value1.desc': { pt: 'Fluência nasce da prática ativa. Colocamos o aluno para falar desde o primeiro dia, sempre com foco em alta performance comunicativa.', en: 'Fluency comes from active practice. We have students speak from day one, always focusing on high communicative performance.', es: 'La fluidez nace de la práctica activa. Ponemos al alumno a hablar desde el primer día, siempre con enfoque en alto rendimiento comunicativo.', fr: 'La fluidité naît de la pratique active. Nous faisons parler l\'élève dès le premier jour, toujours axé sur une haute performance communicative.', it: 'La fluenza nasce dalla pratica attiva. Facciamo parlare l\'allievo dal primo giorno, sempre concentrandoci su alte prestazioni comunicative.' },
    'value2.title': { pt: 'Neurociência aplicada ao aprendizado', en: 'Neuroscience applied to learning', es: 'Neurociencia aplicada al aprendizaje', fr: 'Neuroscience appliquée à l\'apprentissage', it: 'Neuroscienza applicata all\'apprendimento' },
    'value2.desc': { pt: 'Apoiamos nossa metodologia em princípios cognitivos que tornam o progresso mais natural, leve e consistente.', en: 'We support our methodology on cognitive principles that make progress more natural, light, and consistent.', es: 'Apoyamos nuestra metodología en principios cognitivos que hacen el progreso más natural, ligero y consistente.', fr: 'Nous appuyons notre méthodologie sur des principes cognitifs qui rendent les progrès plus naturels, légers et constants.', it: 'Supportiamo la nostra metodologia su principi cognitivi che rendono il progresso più naturale, leggero e costante.' },
    'value3.title': { pt: 'Humanidade no centro', en: 'Humanity at the center', es: 'Humanidad en el centro', fr: 'L\'humanité au centre', it: 'Umanità al centro' },
    'value3.desc': { pt: 'A relação professor aluno é a base da evolução. Valorizamos acolhimento, empatia e um ambiente seguro para desenvolver confiança.', en: 'The teacher-student relationship is the foundation of evolution. We value welcoming, empathy, and a safe environment to develop confidence.', es: 'La relación profesor-alumno es la base de la evolución. Valoramos la acogida, la empatía y un ambiente seguro para desarrollar confianza.', fr: 'La relation enseignant-élève est la base de l\'évolution. Nous valorisons l\'accueil, l\'empathie et un environnement sûr pour développer la confiance.', it: 'Il rapporto insegnante-allievo è la base dell\'evoluzione. Valorizziamo l\'accoglienza, l\'empatia e un ambiente sicuro per sviluppare la fiducia.' },
    'value4.title': { pt: 'Evolução real, evidenciada', en: 'Real, evidenced evolution', es: 'Evolución real, evidenciada', fr: 'Évolution réelle, démontrée', it: 'Evoluzione reale, evidenziata' },
    'value4.desc': { pt: 'Como instituição orientada a resultados, não vendemos aulas. Entregamos progresso mensurável, com métricas claras e acompanhamento contínuo.', en: 'As a results-oriented institution, we don\'t sell classes. We deliver measurable progress, with clear metrics and continuous monitoring.', es: 'Como institución orientada a resultados, no vendemos clases. Entregamos progreso medible, con métricas claras y seguimiento continuo.', fr: 'En tant qu\'institution orientée résultats, nous ne vendons pas de cours. Nous offrons des progrès mesurables, avec des métriques claires et un suivi continu.', it: 'Come istituzione orientata ai risultati, non vendiamo lezioni. Offriamo progressi misurabili, con metriche chiare e monitoraggio continuo.' },
    'value5.title': { pt: 'Respeito à jornada individual', en: 'Respect for individual journey', es: 'Respeto al viaje individual', fr: 'Respect du parcours individuel', it: 'Rispetto del percorso individuale' },
    'value5.desc': { pt: 'Cada aluno tem um ritmo, uma história e um propósito. Nossa metodologia se adapta ao indivíduo para garantir evolução consistente e personalizada.', en: 'Each student has their own rhythm, history, and purpose. Our methodology adapts to the individual to ensure consistent and personalized evolution.', es: 'Cada alumno tiene un ritmo, una historia y un propósito. Nuestra metodología se adapta al individuo para garantizar evolución consistente y personalizada.', fr: 'Chaque élève a son propre rythme, son histoire et son objectif. Notre méthodologie s\'adapte à l\'individu pour garantir une évolution cohérente et personnalisée.', it: 'Ogni allievo ha un proprio ritmo, una storia e uno scopo. La nostra metodologia si adatta all\'individuo per garantire un\'evoluzione coerente e personalizzata.' },
    'value6.title': { pt: 'Inovação com propósito pedagógico', en: 'Innovation with pedagogical purpose', es: 'Innovación con propósito pedagógico', fr: 'Innovation avec objectif pédagogique', it: 'Innovazione con scopo pedagogico' },
    'value6.desc': { pt: 'Utilizamos tecnologia quando ela melhora o aprendizado e potencializa resultados. Inovamos para ampliar fluência, não para dispersar.', en: 'We use technology when it improves learning and enhances results. We innovate to expand fluency, not to disperse.', es: 'Utilizamos tecnología cuando mejora el aprendizaje y potencia resultados. Innovamos para ampliar fluidez, no para dispersar.', fr: 'Nous utilisons la technologie quand elle améliore l\'apprentissage et renforce les résultats. Nous innovons pour étendre la fluidité, pas pour disperser.', it: 'Utilizziamo la tecnologia quando migliora l\'apprendimento e potenzia i risultati. Innoviamo per ampliare la fluenza, non per disperdere.' },
    'value7.title': { pt: 'Excelência como padrão', en: 'Excellence as standard', es: 'Excelencia como estándar', fr: 'L\'excellence comme norme', it: 'Eccellenza come standard' },
    'value7.desc': { pt: 'Comprometidos com formação de alta performance na língua inglesa, buscamos sempre superar expectativas e entregar experiências transformadoras.', en: 'Committed to high-performance English language training, we always seek to exceed expectations and deliver transformative experiences.', es: 'Comprometidos con la formación de alto rendimiento en el idioma inglés, buscamos siempre superar expectativas y entregar experiencias transformadoras.', fr: 'Engagés dans une formation linguistique anglaise de haute performance, nous cherchons toujours à dépasser les attentes et à offrir des expériences transformatrices.', it: 'Impegnati nella formazione ad alte prestazioni nella lingua inglese, cerchiamo sempre di superare le aspettative e offrire esperienze trasformative.' },

    // Footer
    'footer.rights': { pt: 'Todos os direitos reservados.', en: 'All rights reserved.', es: 'Todos los derechos reservados.', fr: 'Tous droits réservés.', it: 'Tutti i diritti riservati.' },
    'footer.description': { pt: 'Acreditamos que fluência não acontece em silêncio. Ela nasce da prática, da coragem de tentar, da orientação certa e de um ambiente que acolhe, inspira e desenvolve. Aqui, cada aula é construída para que você fale, pense e sinta o inglês com naturalidade.', en: 'We believe fluency doesn\'t happen in silence. It comes from practice, the courage to try, the right guidance, and an environment that welcomes, inspires, and develops. Here, every class is built so you speak, think, and feel English naturally.', es: 'Creemos que la fluidez no sucede en silencio. Nace de la práctica, del coraje de intentar, de la orientación correcta y de un ambiente que acoge, inspira y desarrolla. Aquí, cada clase está construida para que hables, pienses y sientas el inglés con naturalidad.', fr: 'Nous croyons que la fluidité ne se produit pas en silence. Elle naît de la pratique, du courage d\'essayer, de la bonne orientation et d\'un environnement qui accueille, inspire et développe. Ici, chaque cours est conçu pour que vous parliez, pensiez et ressentiez l\'anglais naturellement.', it: 'Crediamo che la fluenza non avvenga in silenzio. Nasce dalla pratica, dal coraggio di provare, dalla giusta guida e da un ambiente che accoglie, ispira e sviluppa. Qui, ogni lezione è costruita perché tu parli, pensi e senta l\'inglese con naturalezza.' },
    'footer.quickLinks': { pt: 'Links Rápidos', en: 'Quick Links', es: 'Enlaces Rápidos', fr: 'Liens Rapides', it: 'Link Rapidi' },
    'footer.contact': { pt: 'Contato', en: 'Contact', es: 'Contacto', fr: 'Contact', it: 'Contatto' },
    'footer.socialMedia': { pt: 'Redes Sociais', en: 'Social Media', es: 'Redes Sociales', fr: 'Réseaux Sociaux', it: 'Social Media' },
    'footer.followUs': { pt: 'Siga-nos e fique por dentro de dicas e conteúdos exclusivos', en: 'Follow us and stay up to date with tips and exclusive content', es: 'Síguenos y mantente al día con consejos y contenido exclusivo', fr: 'Suivez-nous et restez informé des astuces et contenus exclusifs', it: 'Seguici e rimani aggiornato con consigli e contenuti esclusivi' },
    'footer.privacy': { pt: 'Política de Privacidade', en: 'Privacy Policy', es: 'Política de Privacidad', fr: 'Politique de Confidentialité', it: 'Politica sulla Privacy' },
    'footer.terms': { pt: 'Termos de Uso', en: 'Terms of Use', es: 'Términos de Uso', fr: 'Conditions d\'Utilisation', it: 'Termini di Utilizzo' },

    // Common
    'common.subscribe': { pt: 'Inscrever-se', en: 'Subscribe', es: 'Inscribirse', fr: 'S\'inscrire', it: 'Iscriversi' },
    'common.learnMore': { pt: 'Saiba mais', en: 'Learn more', es: 'Saber más', fr: 'En savoir plus', it: 'Scopri di più' },
    'common.contact': { pt: 'Contato', en: 'Contact', es: 'Contacto', fr: 'Contact', it: 'Contatto' },
    'common.duration': { pt: 'Duração', en: 'Duration', es: 'Duración', fr: 'Durée', it: 'Durata' },
    'common.instructor': { pt: 'Instrutor', en: 'Instructor', es: 'Instructor', fr: 'Instructeur', it: 'Istruttore' },
    'common.spotsLeft': { pt: 'vagas restantes', en: 'spots left', es: 'vacantes restantes', fr: 'places restantes', it: 'posti disponibili' },
    'common.reserve': { pt: 'Reservar', en: 'Reserve', es: 'Reservar', fr: 'Réserver', it: 'Prenota' },
    'common.popular': { pt: 'Popular', en: 'Popular', es: 'Popular', fr: 'Populaire', it: 'Popolare' },

    // Specific Courses Page - Hero
    'specificCourses.hero.title': { pt: 'Cursos', en: 'Specific', es: 'Cursos', fr: 'Cours', it: 'Corsi' },
    'specificCourses.hero.titleHighlight': { pt: 'Específicos', en: 'Courses', es: 'Específicos', fr: 'Spécifiques', it: 'Specifici' },
    'specificCourses.hero.subtitle': { pt: 'Aprimore habilidades específicas com nossos cursos complementares e workshops intensivos ministrados por especialistas.', en: 'Improve specific skills with our complementary courses and intensive workshops taught by specialists.', es: 'Mejora habilidades específicas con nuestros cursos complementarios y talleres intensivos impartidos por especialistas.', fr: 'Améliorez des compétences spécifiques avec nos cours complémentaires et ateliers intensifs dispensés par des spécialistes.', it: 'Migliora competenze specifiche con i nostri corsi complementari e workshop intensivi tenuti da specialisti.' },

    // Specific Courses - Specialized Section
    'specificCourses.specialized.title': { pt: 'Cursos', en: 'Specialized', es: 'Cursos', fr: 'Cours', it: 'Corsi' },
    'specificCourses.specialized.titleHighlight': { pt: 'Especializados', en: 'Courses', es: 'Especializados', fr: 'Spécialisés', it: 'Specializzati' },
    'specificCourses.specialized.subtitle': { pt: 'Focados em habilidades específicas para acelerar seu desenvolvimento profissional', en: 'Focused on specific skills to accelerate your professional development', es: 'Enfocados en habilidades específicas para acelerar tu desarrollo profesional', fr: 'Axés sur des compétences spécifiques pour accélérer votre développement professionnel', it: 'Focalizzati su competenze specifiche per accelerare il tuo sviluppo professionale' },
    'specificCourses.popular': { pt: 'Popular', en: 'Popular', es: 'Popular', fr: 'Populaire', it: 'Popolare' },
    'specificCourses.enroll': { pt: 'Inscrever-se', en: 'Enroll', es: 'Inscribirse', fr: 'S\'inscrire', it: 'Iscriviti' },

    // Specific Courses - Course Items
    'specificCourses.courses.presentations.title': { pt: 'Inglês para Apresentações', en: 'English for Presentations', es: 'Inglés para Presentaciones', fr: 'Anglais pour Présentations', it: 'Inglese per Presentazioni' },
    'specificCourses.courses.presentations.description': { pt: 'Domine a arte de apresentar em inglês com confiança e impacto.', en: 'Master the art of presenting in English with confidence and impact.', es: 'Domina el arte de presentar en inglés con confianza e impacto.', fr: 'Maîtrisez l\'art de présenter en anglais avec confiance et impact.', it: 'Padroneggia l\'arte di presentare in inglese con fiducia e impatto.' },
    'specificCourses.courses.presentations.duration': { pt: '8 semanas', en: '8 weeks', es: '8 semanas', fr: '8 semaines', it: '8 settimane' },
    'specificCourses.courses.presentations.level': { pt: 'Intermediário', en: 'Intermediate', es: 'Intermedio', fr: 'Intermédiaire', it: 'Intermedio' },
    'specificCourses.courses.presentations.feature1': { pt: 'Técnicas de oratória', en: 'Public speaking techniques', es: 'Técnicas de oratoria', fr: 'Techniques d\'éloquence', it: 'Tecniche di oratoria' },
    'specificCourses.courses.presentations.feature2': { pt: 'Vocabulário corporativo', en: 'Corporate vocabulary', es: 'Vocabulario corporativo', fr: 'Vocabulaire d\'entreprise', it: 'Vocabolario aziendale' },
    'specificCourses.courses.presentations.feature3': { pt: 'Prática com feedback', en: 'Practice with feedback', es: 'Práctica con feedback', fr: 'Pratique avec feedback', it: 'Pratica con feedback' },
    'specificCourses.courses.presentations.feature4': { pt: 'Material exclusivo', en: 'Exclusive material', es: 'Material exclusivo', fr: 'Matériel exclusif', it: 'Materiale esclusivo' },

    'specificCourses.courses.businessWriting.title': { pt: 'Business Writing', en: 'Business Writing', es: 'Business Writing', fr: 'Business Writing', it: 'Business Writing' },
    'specificCourses.courses.businessWriting.description': { pt: 'Aprenda a escrever e-mails, relatórios e documentos profissionais.', en: 'Learn to write emails, reports, and professional documents.', es: 'Aprende a escribir correos, informes y documentos profesionales.', fr: 'Apprenez à rédiger des emails, rapports et documents professionnels.', it: 'Impara a scrivere email, report e documenti professionali.' },
    'specificCourses.courses.businessWriting.duration': { pt: '6 semanas', en: '6 weeks', es: '6 semanas', fr: '6 semaines', it: '6 settimane' },
    'specificCourses.courses.businessWriting.level': { pt: 'Intermediário', en: 'Intermediate', es: 'Intermedio', fr: 'Intermédiaire', it: 'Intermedio' },
    'specificCourses.courses.businessWriting.feature1': { pt: 'E-mails profissionais', en: 'Professional emails', es: 'Emails profesionales', fr: 'Emails professionnels', it: 'Email professionali' },
    'specificCourses.courses.businessWriting.feature2': { pt: 'Relatórios executivos', en: 'Executive reports', es: 'Informes ejecutivos', fr: 'Rapports exécutifs', it: 'Report esecutivi' },
    'specificCourses.courses.businessWriting.feature3': { pt: 'Propostas comerciais', en: 'Business proposals', es: 'Propuestas comerciales', fr: 'Propositions commerciales', it: 'Proposte commerciali' },
    'specificCourses.courses.businessWriting.feature4': { pt: 'Revisão personalizada', en: 'Personalized review', es: 'Revisión personalizada', fr: 'Révision personnalisée', it: 'Revisione personalizzata' },

    'specificCourses.courses.listening.title': { pt: 'Listening Intensivo', en: 'Intensive Listening', es: 'Listening Intensivo', fr: 'Écoute Intensive', it: 'Ascolto Intensivo' },
    'specificCourses.courses.listening.description': { pt: 'Desenvolva sua compreensão auditiva com sotaques variados.', en: 'Develop your listening comprehension with varied accents.', es: 'Desarrolla tu comprensión auditiva con acentos variados.', fr: 'Développez votre compréhension orale avec des accents variés.', it: 'Sviluppa la tua comprensione uditiva con accenti vari.' },
    'specificCourses.courses.listening.duration': { pt: '4 semanas', en: '4 weeks', es: '4 semanas', fr: '4 semaines', it: '4 settimane' },
    'specificCourses.courses.listening.level': { pt: 'Todos os níveis', en: 'All levels', es: 'Todos los niveles', fr: 'Tous les niveaux', it: 'Tutti i livelli' },
    'specificCourses.courses.listening.feature1': { pt: 'Sotaques americano/britânico', en: 'American/British accents', es: 'Acentos americano/británico', fr: 'Accents américain/britannique', it: 'Accenti americano/britannico' },
    'specificCourses.courses.listening.feature2': { pt: 'Podcasts e vídeos', en: 'Podcasts and videos', es: 'Podcasts y videos', fr: 'Podcasts et vidéos', it: 'Podcast e video' },
    'specificCourses.courses.listening.feature3': { pt: 'Exercícios diários', en: 'Daily exercises', es: 'Ejercicios diarios', fr: 'Exercices quotidiens', it: 'Esercizi quotidiani' },
    'specificCourses.courses.listening.feature4': { pt: 'Feedback de pronúncia', en: 'Pronunciation feedback', es: 'Feedback de pronunciación', fr: 'Feedback de prononciation', it: 'Feedback di pronuncia' },

    'specificCourses.courses.meetings.title': { pt: 'Inglês para Reuniões', en: 'English for Meetings', es: 'Inglés para Reuniones', fr: 'Anglais pour Réunions', it: 'Inglese per Riunioni' },
    'specificCourses.courses.meetings.description': { pt: 'Conduza e participe de reuniões em inglês com naturalidade.', en: 'Lead and participate in meetings in English naturally.', es: 'Conduce y participa en reuniones en inglés con naturalidad.', fr: 'Menez et participez à des réunions en anglais naturellement.', it: 'Conduci e partecipa a riunioni in inglese con naturalezza.' },
    'specificCourses.courses.meetings.duration': { pt: '6 semanas', en: '6 weeks', es: '6 semanas', fr: '6 semaines', it: '6 settimane' },
    'specificCourses.courses.meetings.level': { pt: 'Intermediário+', en: 'Intermediate+', es: 'Intermedio+', fr: 'Intermédiaire+', it: 'Intermedio+' },
    'specificCourses.courses.meetings.feature1': { pt: 'Vocabulário de reuniões', en: 'Meeting vocabulary', es: 'Vocabulario de reuniones', fr: 'Vocabulaire de réunion', it: 'Vocabolario di riunioni' },
    'specificCourses.courses.meetings.feature2': { pt: 'Expressões de negociação', en: 'Negotiation expressions', es: 'Expresiones de negociación', fr: 'Expressions de négociation', it: 'Espressioni di negoziazione' },
    'specificCourses.courses.meetings.feature3': { pt: 'Simulações práticas', en: 'Practical simulations', es: 'Simulaciones prácticas', fr: 'Simulations pratiques', it: 'Simulazioni pratiche' },
    'specificCourses.courses.meetings.feature4': { pt: 'Role-playing', en: 'Role-playing', es: 'Role-playing', fr: 'Jeux de rôle', it: 'Role-playing' },

    'specificCourses.courses.toefl.title': { pt: 'TOEFL Preparation', en: 'TOEFL Preparation', es: 'TOEFL Preparation', fr: 'Préparation TOEFL', it: 'Preparazione TOEFL' },
    'specificCourses.courses.toefl.description': { pt: 'Preparação completa para o exame TOEFL com simulados.', en: 'Complete preparation for the TOEFL exam with mock tests.', es: 'Preparación completa para el examen TOEFL con simulacros.', fr: 'Préparation complète à l\'examen TOEFL avec des tests blancs.', it: 'Preparazione completa per l\'esame TOEFL con simulazioni.' },
    'specificCourses.courses.toefl.duration': { pt: '12 semanas', en: '12 weeks', es: '12 semanas', fr: '12 semaines', it: '12 settimane' },
    'specificCourses.courses.toefl.level': { pt: 'Intermediário+', en: 'Intermediate+', es: 'Intermedio+', fr: 'Intermédiaire+', it: 'Intermedio+' },
    'specificCourses.courses.toefl.feature1': { pt: 'Simulados completos', en: 'Complete mock tests', es: 'Simulacros completos', fr: 'Tests blancs complets', it: 'Simulazioni complete' },
    'specificCourses.courses.toefl.feature2': { pt: 'Estratégias por seção', en: 'Section strategies', es: 'Estrategias por sección', fr: 'Stratégies par section', it: 'Strategie per sezione' },
    'specificCourses.courses.toefl.feature3': { pt: 'Material oficial', en: 'Official material', es: 'Material oficial', fr: 'Matériel officiel', it: 'Materiale ufficiale' },
    'specificCourses.courses.toefl.feature4': { pt: 'Garantia de resultado', en: 'Result guarantee', es: 'Garantía de resultado', fr: 'Garantie de résultat', it: 'Garanzia di risultato' },

    'specificCourses.courses.networking.title': { pt: 'Networking em Inglês', en: 'Networking in English', es: 'Networking en Inglés', fr: 'Networking en Anglais', it: 'Networking in Inglese' },
    'specificCourses.courses.networking.description': { pt: 'Construa conexões profissionais em eventos e plataformas.', en: 'Build professional connections at events and platforms.', es: 'Construye conexiones profesionales en eventos y plataformas.', fr: 'Construisez des connexions professionnelles lors d\'événements et plateformes.', it: 'Costruisci connessioni professionali in eventi e piattaforme.' },
    'specificCourses.courses.networking.duration': { pt: '4 semanas', en: '4 weeks', es: '4 semanas', fr: '4 semaines', it: '4 settimane' },
    'specificCourses.courses.networking.level': { pt: 'Intermediário', en: 'Intermediate', es: 'Intermedio', fr: 'Intermédiaire', it: 'Intermedio' },
    'specificCourses.courses.networking.feature1': { pt: 'Small talk', en: 'Small talk', es: 'Small talk', fr: 'Small talk', it: 'Small talk' },
    'specificCourses.courses.networking.feature2': { pt: 'LinkedIn em inglês', en: 'LinkedIn in English', es: 'LinkedIn en inglés', fr: 'LinkedIn en anglais', it: 'LinkedIn in inglese' },
    'specificCourses.courses.networking.feature3': { pt: 'Pitch pessoal', en: 'Personal pitch', es: 'Pitch personal', fr: 'Pitch personnel', it: 'Pitch personale' },
    'specificCourses.courses.networking.feature4': { pt: 'Eventos simulados', en: 'Simulated events', es: 'Eventos simulados', fr: 'Événements simulés', it: 'Eventi simulati' },

    // Specific Courses - Workshops Section
    'specificCourses.workshopsSection.title': { pt: 'Workshops', en: 'Live', es: 'Workshops', fr: 'Ateliers', it: 'Workshop' },
    'specificCourses.workshopsSection.titleHighlight': { pt: 'Ao Vivo', en: 'Workshops', es: 'En Vivo', fr: 'En Direct', it: 'Dal Vivo' },
    'specificCourses.workshopsSection.subtitle': { pt: 'Sessões intensivas com interação em tempo real e vagas limitadas', en: 'Intensive sessions with real-time interaction and limited spots', es: 'Sesiones intensivas con interacción en tiempo real y cupos limitados', fr: 'Sessions intensives avec interaction en temps réel et places limitées', it: 'Sessioni intensive con interazione in tempo reale e posti limitati' },
    'specificCourses.workshopsSection.at': { pt: 'às', en: 'at', es: 'a las', fr: 'à', it: 'alle' },
    'specificCourses.workshopsSection.duration': { pt: 'Duração', en: 'Duration', es: 'Duración', fr: 'Durée', it: 'Durata' },
    'specificCourses.workshopsSection.instructor': { pt: 'Instrutor', en: 'Instructor', es: 'Instructor', fr: 'Instructeur', it: 'Istruttore' },
    'specificCourses.workshopsSection.spotsLeft': { pt: 'vagas restantes', en: 'spots left', es: 'vacantes restantes', fr: 'places restantes', it: 'posti rimanenti' },
    'specificCourses.workshopsSection.reserve': { pt: 'Reservar', en: 'Reserve', es: 'Reservar', fr: 'Réserver', it: 'Prenota' },

    'specificCourses.workshops.pronunciation.title': { pt: 'Pronúncia Americana', en: 'American Pronunciation', es: 'Pronunciación Americana', fr: 'Prononciation Américaine', it: 'Pronuncia Americana' },
    'specificCourses.workshops.pronunciation.duration': { pt: '2 horas', en: '2 hours', es: '2 horas', fr: '2 heures', it: '2 ore' },
    'specificCourses.workshops.phrasalVerbs.title': { pt: 'Phrasal Verbs Essenciais', en: 'Essential Phrasal Verbs', es: 'Phrasal Verbs Esenciales', fr: 'Phrasal Verbs Essentiels', it: 'Phrasal Verbs Essenziali' },
    'specificCourses.workshops.phrasalVerbs.duration': { pt: '2 horas', en: '2 hours', es: '2 horas', fr: '2 heures', it: '2 ore' },
    'specificCourses.workshops.tech.title': { pt: 'Inglês para Tech', en: 'English for Tech', es: 'Inglés para Tech', fr: 'Anglais pour Tech', it: 'Inglese per Tech' },
    'specificCourses.workshops.tech.duration': { pt: '3 horas', en: '3 hours', es: '3 horas', fr: '3 heures', it: '3 ore' },

    // Specific Courses - CTA Section
    'specificCourses.cta.title': { pt: 'Não encontrou o que procura?', en: 'Didn\'t find what you\'re looking for?', es: '¿No encontraste lo que buscas?', fr: 'Vous n\'avez pas trouvé ce que vous cherchez?', it: 'Non hai trovato quello che cerchi?' },
    'specificCourses.cta.subtitle': { pt: 'Entre em contato conosco e criaremos um programa personalizado para suas necessidades.', en: 'Contact us and we\'ll create a personalized program for your needs.', es: 'Contáctanos y crearemos un programa personalizado para tus necesidades.', fr: 'Contactez-nous et nous créerons un programme personnalisé pour vos besoins.', it: 'Contattaci e creeremo un programma personalizzato per le tue esigenze.' },
    'specificCourses.cta.button': { pt: 'Fale com um Consultor', en: 'Talk to a Consultant', es: 'Habla con un Consultor', fr: 'Parlez à un Consultant', it: 'Parla con un Consulente' },

    // Corporate English Page
    'corporate.whyInvest': { pt: 'Por que investir em', en: 'Why invest in', es: '¿Por qué invertir en', fr: 'Pourquoi investir dans', it: 'Perché investire in' },
    'corporate.whyInvestHighlight': { pt: 'inglês corporativo?', en: 'corporate English?', es: 'inglés corporativo?', fr: 'l\'anglais des affaires?', it: 'inglese aziendale?' },
    'corporate.whyInvestSubtitle': { pt: 'Empresas que investem no desenvolvimento linguístico dos colaboradores colhem resultados expressivos', en: 'Companies that invest in employees\' language development reap significant results', es: 'Las empresas que invierten en el desarrollo lingüístico de los colaboradores cosechan resultados expresivos', fr: 'Les entreprises qui investissent dans le développement linguistique des employés récoltent des résultats significatifs', it: 'Le aziende che investono nello sviluppo linguistico dei collaboratori raccolgono risultati significativi' },
    'corporate.packagesTitle': { pt: 'Pacotes', en: 'Business', es: 'Paquetes', fr: 'Forfaits', it: 'Pacchetti' },
    'corporate.packagesHighlight': { pt: 'Empresariais', en: 'Packages', es: 'Empresariales', fr: 'Entreprise', it: 'Aziendali' },
    'corporate.packagesSubtitle': { pt: 'Soluções flexíveis que se adaptam ao tamanho e às necessidades da sua empresa', en: 'Flexible solutions that adapt to your company\'s size and needs', es: 'Soluciones flexibles que se adaptan al tamaño y necesidades de tu empresa', fr: 'Solutions flexibles qui s\'adaptent à la taille et aux besoins de votre entreprise', it: 'Soluzioni flessibili che si adattano alla dimensione e alle esigenze della tua azienda' },
    'corporate.howItWorks': { pt: 'Como', en: 'How It', es: 'Cómo', fr: 'Comment ça', it: 'Come' },
    'corporate.howItWorksHighlight': { pt: 'Funciona', en: 'Works', es: 'Funciona', fr: 'Fonctionne', it: 'Funziona' },
    'corporate.howItWorksSubtitle': { pt: 'Um processo simples e eficiente para implementar o inglês na sua empresa', en: 'A simple and efficient process to implement English in your company', es: 'Un proceso simple y eficiente para implementar el inglés en tu empresa', fr: 'Un processus simple et efficace pour mettre en œuvre l\'anglais dans votre entreprise', it: 'Un processo semplice ed efficiente per implementare l\'inglese nella tua azienda' },
    'corporate.ctaTitle': { pt: 'Pronto para transformar sua equipe?', en: 'Ready to transform your team?', es: '¿Listo para transformar tu equipo?', fr: 'Prêt à transformer votre équipe?', it: 'Pronto a trasformare il tuo team?' },
    'corporate.ctaSubtitle': { pt: 'Entre em contato e receba uma proposta personalizada para sua empresa.', en: 'Contact us and receive a personalized proposal for your company.', es: 'Contáctanos y recibe una propuesta personalizada para tu empresa.', fr: 'Contactez-nous et recevez une proposition personnalisée pour votre entreprise.', it: 'Contattaci e ricevi una proposta personalizzata per la tua azienda.' },
    'corporate.talkToSpecialist': { pt: 'Falar com Especialista', en: 'Talk to Specialist', es: 'Hablar con Especialista', fr: 'Parler à un Spécialiste', it: 'Parla con uno Specialista' },
    'corporate.requestProposal': { pt: 'Solicitar Proposta', en: 'Request Proposal', es: 'Solicitar Propuesta', fr: 'Demander une Proposition', it: 'Richiedi Proposta' },
    'corporate.productivityIncrease': { pt: 'Aumento de Produtividade', en: 'Productivity Increase', es: 'Aumento de Productividad', fr: 'Augmentation de la Productivité', it: 'Aumento della Produttività' },
    'corporate.productivityDesc': { pt: 'Colaboradores fluentes em inglês se comunicam melhor com clientes e parceiros internacionais.', en: 'Fluent English-speaking employees communicate better with international clients and partners.', es: 'Los colaboradores fluentes en inglés se comunican mejor con clientes y socios internacionales.', fr: 'Les employés parlant couramment anglais communiquent mieux avec les clients et partenaires internationaux.', it: 'I collaboratori fluenti in inglese comunicano meglio con clienti e partner internazionali.' },
    'corporate.internationalExpansion': { pt: 'Expansão Internacional', en: 'International Expansion', es: 'Expansión Internacional', fr: 'Expansion Internationale', it: 'Espansione Internazionale' },
    'corporate.expansionDesc': { pt: 'Prepare sua equipe para mercados globais e oportunidades de negócios internacionais.', en: 'Prepare your team for global markets and international business opportunities.', es: 'Prepara tu equipo para mercados globales y oportunidades de negocios internacionales.', fr: 'Préparez votre équipe pour les marchés mondiaux et les opportunités commerciales internationales.', it: 'Prepara il tuo team per mercati globali e opportunità di business internazionali.' },
    'corporate.talentRetention': { pt: 'Retenção de Talentos', en: 'Talent Retention', es: 'Retención de Talentos', fr: 'Rétention des Talents', it: 'Ritenzione dei Talenti' },
    'corporate.retentionDesc': { pt: 'Investir no desenvolvimento dos colaboradores aumenta o engajamento e reduz turnover.', en: 'Investing in employee development increases engagement and reduces turnover.', es: 'Invertir en el desarrollo de los colaboradores aumenta el compromiso y reduce la rotación.', fr: 'Investir dans le développement des employés augmente l\'engagement et réduit le turnover.', it: 'Investire nello sviluppo dei collaboratori aumenta il coinvolgimento e riduce il turnover.' },
    'corporate.competitiveness': { pt: 'Competitividade', en: 'Competitiveness', es: 'Competitividad', fr: 'Compétitivité', it: 'Competitività' },
    'corporate.competitivenessDesc': { pt: 'Equipes bilíngues são mais competitivas no mercado atual globalizado.', en: 'Bilingual teams are more competitive in today\'s globalized market.', es: 'Los equipos bilingües son más competitivos en el mercado globalizado actual.', fr: 'Les équipes bilingues sont plus compétitives sur le marché mondialisé d\'aujourd\'hui.', it: 'I team bilingui sono più competitivi nel mercato globalizzato di oggi.' },

    // Corporate - Packages
    'corporate.sprint': { pt: 'Sprint', en: 'Sprint', es: 'Sprint', fr: 'Sprint', it: 'Sprint' },
    'corporate.sprintDesc': { pt: 'Imersão rápida para acelerar sua fala', en: 'Fast immersion to accelerate your speech', es: 'Inmersión rápida para acelerar tu habla', fr: 'Immersion rapide pour accélérer votre parole', it: 'Immersione rapida per accelerare il tuo parlato' },
    'corporate.sprintHours': { pt: '12h para Falar Inglês', en: '12h to Speak English', es: '12h para Hablar Inglés', fr: '12h pour Parler Anglais', it: '12h per Parlare Inglese' },
    'corporate.gold': { pt: 'Gold', en: 'Gold', es: 'Gold', fr: 'Gold', it: 'Gold' },
    'corporate.goldDesc': { pt: 'Evolução consistente com mais prática guiada', en: 'Consistent evolution with more guided practice', es: 'Evolución consistente con más práctica guiada', fr: 'Évolution constante avec plus de pratique guidée', it: 'Evoluzione costante con più pratica guidata' },
    'corporate.goldHours': { pt: '24h para Falar Inglês', en: '24h to Speak English', es: '24h para Hablar Inglés', fr: '24h pour Parler Anglais', it: '24h per Parlare Inglese' },
    'corporate.premium': { pt: 'Premium', en: 'Premium', es: 'Premium', fr: 'Premium', it: 'Premium' },
    'corporate.premiumDesc': { pt: 'Alta performance para quem quer avançar no máximo nível', en: 'High performance for those who want to advance at the highest level', es: 'Alto rendimiento para quienes quieren avanzar al máximo nivel', fr: 'Haute performance pour ceux qui veulent progresser au plus haut niveau', it: 'Alta performance per chi vuole avanzare al massimo livello' },
    'corporate.premiumHours': { pt: '30h para Falar Inglês', en: '30h to Speak English', es: '30h para Hablar Inglés', fr: '30h pour Parler Anglais', it: '30h per Parlare Inglese' },
    'corporate.mostPopular': { pt: 'Mais Popular', en: 'Most Popular', es: 'Más Popular', fr: 'Le Plus Populaire', it: 'Più Popolare' },

    // Corporate - Package Features
    'corporate.feature.4hours': { pt: '4 horas mensais – 2 aulas ao vivo de 30 min por semana', en: '4 monthly hours – 2 live classes of 30 min per week', es: '4 horas mensuales – 2 clases en vivo de 30 min por semana', fr: '4 heures mensuelles – 2 cours en direct de 30 min par semaine', it: '4 ore mensili – 2 lezioni live di 30 min a settimana' },
    'corporate.feature.8hours': { pt: '8 horas mensais – 4 aulas ao vivo de 30 min por semana', en: '8 monthly hours – 4 live classes of 30 min per week', es: '8 horas mensuales – 4 clases en vivo de 30 min por semana', fr: '8 heures mensuelles – 4 cours en direct de 30 min par semaine', it: '8 ore mensili – 4 lezioni live di 30 min a settimana' },
    'corporate.feature.10hours': { pt: '10 horas mensais – 5 aulas ao vivo de 30 min por semana', en: '10 monthly hours – 5 live classes of 30 min per week', es: '10 horas mensuales – 5 clases en vivo de 30 min por semana', fr: '10 heures mensuelles – 5 cours en direct de 30 min par semaine', it: '10 ore mensili – 5 lezioni live di 30 min a settimana' },
    'corporate.feature.unlimitedPlatform': { pt: 'Acesso ilimitado à plataforma de vídeo aulas', en: 'Unlimited access to video class platform', es: 'Acceso ilimitado a la plataforma de video clases', fr: 'Accès illimité à la plateforme de vidéo-cours', it: 'Accesso illimitato alla piattaforma di video lezioni' },
    'corporate.feature.materialIncluded': { pt: 'Material sem custo adicional - incluso no plano', en: 'Material at no additional cost - included in the plan', es: 'Material sin costo adicional - incluido en el plan', fr: 'Matériel sans frais supplémentaires - inclus dans le forfait', it: 'Materiale senza costi aggiuntivi - incluso nel piano' },
    'corporate.feature.tripleGuarantee': { pt: 'Garantia Tríplice Exclusiva', en: 'Exclusive Triple Guarantee', es: 'Garantía Triple Exclusiva', fr: 'Garantie Triple Exclusive', it: 'Garanzia Tripla Esclusiva' },
    'corporate.feature.nagibe': { pt: '3 aulas semanais de 45 minutos com o Nagibe, professor e CEO da Speak, ao vivo', en: '3 weekly 45-minute classes with Nagibe, teacher and CEO of Speak, live', es: '3 clases semanales de 45 minutos con Nagibe, profesor y CEO de Speak, en vivo', fr: '3 cours hebdomadaires de 45 minutes avec Nagibe, professeur et PDG de Speak, en direct', it: '3 lezioni settimanali di 45 minuti con Nagibe, professore e CEO di Speak, dal vivo' },
    'corporate.feature.allBenefits': { pt: 'Todos os benefícios dos Planos Sprint e Gold', en: 'All benefits of Sprint and Gold Plans', es: 'Todos los beneficios de los Planes Sprint y Gold', fr: 'Tous les avantages des Plans Sprint et Gold', it: 'Tutti i vantaggi dei Piani Sprint e Gold' },
    'corporate.feature.diagnosis': { pt: 'Diagnóstico Linguístico Inicial', en: 'Initial Linguistic Diagnosis', es: 'Diagnóstico Lingüístico Inicial', fr: 'Diagnostic Linguistique Initial', it: 'Diagnosi Linguistica Iniziale' },
    'corporate.feature.mentorship': { pt: 'Mentoria e Plano de Crescimento on demand', en: 'On-demand Mentorship and Growth Plan', es: 'Mentoría y Plan de Crecimiento on demand', fr: 'Mentorat et Plan de Croissance à la demande', it: 'Mentoring e Piano di Crescita on demand' },

    // Corporate - Process Steps
    'corporate.process.diagnosis': { pt: 'Diagnóstico', en: 'Diagnosis', es: 'Diagnóstico', fr: 'Diagnostic', it: 'Diagnosi' },
    'corporate.process.diagnosisDesc': { pt: 'Avaliamos o nível de cada colaborador e entendemos os objetivos da empresa.', en: 'We assess each employee\'s level and understand the company\'s objectives.', es: 'Evaluamos el nivel de cada colaborador y entendemos los objetivos de la empresa.', fr: 'Nous évaluons le niveau de chaque employé et comprenons les objectifs de l\'entreprise.', it: 'Valutiamo il livello di ogni collaboratore e comprendiamo gli obiettivi dell\'azienda.' },
    'corporate.process.customProgram': { pt: 'Programa Personalizado', en: 'Customized Program', es: 'Programa Personalizado', fr: 'Programme Personnalisé', it: 'Programma Personalizzato' },
    'corporate.process.customProgramDesc': { pt: 'Criamos um programa sob medida para as necessidades específicas do seu negócio.', en: 'We create a tailored program for your business\'s specific needs.', es: 'Creamos un programa a medida para las necesidades específicas de tu negocio.', fr: 'Nous créons un programme sur mesure pour les besoins spécifiques de votre entreprise.', it: 'Creiamo un programma su misura per le esigenze specifiche del tuo business.' },
    'corporate.process.implementation': { pt: 'Implementação', en: 'Implementation', es: 'Implementación', fr: 'Mise en Œuvre', it: 'Implementazione' },
    'corporate.process.implementationDesc': { pt: 'Iniciamos as aulas com horários flexíveis que se adaptam à rotina da empresa.', en: 'We start classes with flexible schedules that adapt to the company\'s routine.', es: 'Iniciamos las clases con horarios flexibles que se adaptan a la rutina de la empresa.', fr: 'Nous commençons les cours avec des horaires flexibles qui s\'adaptent à la routine de l\'entreprise.', it: 'Iniziamo le lezioni con orari flessibili che si adattano alla routine dell\'azienda.' },
    'corporate.process.followUp': { pt: 'Acompanhamento', en: 'Follow-up', es: 'Seguimiento', fr: 'Suivi', it: 'Monitoraggio' },
    'corporate.process.followUpDesc': { pt: 'Monitoramos o progresso e ajustamos o programa conforme necessário.', en: 'We monitor progress and adjust the program as needed.', es: 'Monitoreamos el progreso y ajustamos el programa según sea necesario.', fr: 'Nous suivons les progrès et ajustons le programme selon les besoins.', it: 'Monitoriamo i progressi e adattiamo il programma secondo necessità.' },

    // WhatsApp
    'whatsapp.greeting': { pt: 'Olá! Eu vim através do site e quero informações sobre', en: 'Hello! I came through the website and I want information about', es: '¡Hola! Llegué a través del sitio web y quiero información sobre', fr: 'Bonjour! Je suis venu par le site web et je veux des informations sur', it: 'Ciao! Sono arrivato tramite il sito web e voglio informazioni su' },
    'whatsapp.generalCourse': { pt: 'os cursos', en: 'the courses', es: 'los cursos', fr: 'les cours', it: 'i corsi' },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('pt');

    const t = (key: string): string => {
        if (translations[key] && translations[key][language]) {
            return translations[key][language];
        }
        console.warn(`Translation missing for key: ${key}`);
        return key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
